FROM mcr.microsoft.com/playwright:v1.55.0-jammy@sha256:55db7b712a981e9cc1ec757a4511cd01c5ed4e20bd7c84b2dee4e1d320102b9d
USER root
RUN apt-get update && apt-get install -y --no-install-recommends build-essential clang patch openjdk-21-jdk-headless && rm -rf /var/lib/apt/lists/*
